### ISSUE TITLE
Create docs website

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-sdk#5]
We have to create a pipeline with a github action for creating an sdk docs website, we can publish on the the repo github pages.

Currently we're doing something similar with the `vyper-cli` project [here](https://github.com/vyper-protocol/vyper-cli/blob/dev/.github/workflows/cargo-docs.yml) published [here](https://vyper-protocol.github.io/vyper-cli/vyper/).

We'll use [TypeDoc](https://typedoc.org/) or something similar.

The docs will be aligned with the main branch, so for example in the gh action:
```yml
name: publish typedocs
on:
  push:
    branches:
      - "main"
```
